### ISSUE TITLE
Error when importing GLFM

### ISSUE THREAD

**Issue by xukai92** [ivaleraM/GLFM#1]
I followed the installation guide for Python and was trying the `demo_toy_images.ipynb` demo.

I came up with this error when running `import GLFM`.

```python
------------------------------------------------------------------
ImportError                      Traceback (most recent call last)
<ipython-input-5-005cc9d9c0ea> in <module>()
      8 sys.path.append('/Users/kai/projects/GLFM/src/GLFMpython')
      9 sys.path.append('/Users/kai/projects/GLFM/Ccode/wrapper_python')
---> 10 import GLFM
     11 
     12 import pdb

/Users/kai/projects/GLFM/src/GLFMpython/GLFM.py in <module>()
     11 sys.path.append(os.path.join(root, 'Ccode/wrapper_python/'))
     12 
---> 13 import GLFMlib # python wrapper library in order to run C++ inference routine
     14 import mapping_functions as mf
     15 

ImportError: dlopen(/Users/kai/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so, 2): Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Users/kai/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so
  Reason: image not found
```

NB: I already updated `sys.path.append('/Users/kai/projects/GLFM/src/GLFMpython')` to the corresponding path of my local repo directory.

Any idea what's the reason?

**Comment by ivaleraM** [comment]
Hi Kai,

I copy below the response of Melanie (in CC), who is the person that developed the python interface:

"The error occurs because the GLFMlib.so library is not found.
Maybe it was not generated properly. Please verify that the file exists,
if not, execute again:
	- Go to src/src/Ccode/wrapper_python/ folder
	- run command from terminal: python setup.py build_ext –inplace
and send us the error message, if any."

Thanks for your feedback and let us know how we can help you out.

Cheers,
Isabel

**Comment by xukai92** [comment]
Hi Isabel,

I checked my `src/Ccode/wrapper_python` and there is a file called `GLFMlib.so`. Do I need to somehow include this?

Yours,

Kai

**Comment by ivaleraM** [comment]
You nee to import the library before making a call, for example: 
import GLFM
(hidden) = GLFM.infer(data)
Melanie, any further comments?

Thanks,
Isabel

**Comment by xukai92** [comment]
Yes - but the error occurs when I do `import GLFM`. It seems to me that my Python doesn't find the `.so` file?

**Comment by ivaleraM** [comment]
Do you get any error when compile the code using the command "python setup.py build_ext --inplace" in the "src/Ccode/wrapper_python/" folder?

In such case, can you copy it to us?

Thanks,
Isabel

**Comment by xukai92** [comment]
I didn't see any error during my compilation. FYI, below is my compilation log

```bash
(glfm) ➜  wrapper_python (master) ✔ python setup.py build_ext --inplace
running build_ext
cythoning GLFM.pyx to GLFM.cpp
building 'GLFMlib' extension
creating build
creating build/temp.macosx-10.7-x86_64-2.7
creating build/core
gcc -fno-strict-aliasing -I/Users/kai/miniconda2/envs/glfm/include -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/X11/include -arch x86_64 -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages -I/Users/kai/miniconda2/envs/glfm/include -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages/numpy/core/include -I/Users/kai/miniconda2/envs/glfm/include/python2.7 -c GLFM.cpp -o build/temp.macosx-10.7-x86_64-2.7/GLFM.o -w
gcc -fno-strict-aliasing -I/Users/kai/miniconda2/envs/glfm/include -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/X11/include -arch x86_64 -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages -I/Users/kai/miniconda2/envs/glfm/include -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages/numpy/core/include -I/Users/kai/miniconda2/envs/glfm/include/python2.7 -c ../core/GeneralFunctions.cpp -o build/temp.macosx-10.7-x86_64-2.7/../core/GeneralFunctions.o -w
gcc -fno-strict-aliasing -I/Users/kai/miniconda2/envs/glfm/include -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/X11/include -arch x86_64 -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages -I/Users/kai/miniconda2/envs/glfm/include -I/Users/kai/miniconda2/envs/glfm/lib/python2.7/site-packages/numpy/core/include -I/Users/kai/miniconda2/envs/glfm/include/python2.7 -c ../core/InferenceFunctions.cpp -o build/temp.macosx-10.7-x86_64-2.7/../core/InferenceFunctions.o -w
g++ -bundle -undefined dynamic_lookup -L/Users/kai/miniconda2/envs/glfm/lib -I/opt/X11/include -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-2.7/GLFM.o build/temp.macosx-10.7-x86_64-2.7/../core/GeneralFunctions.o build/temp.macosx-10.7-x86_64-2.7/../core/InferenceFunctions.o -L/Users/kai/miniconda2/envs/glfm/lib -L/Users/kai/miniconda2/envs/glfm/lib -lgsl -lgslcblas -o /Users/kai/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
```

**Comment by ivaleraM** [comment]
try with:

>> sys.path.append('../../src/GLFMpython/')
>> import GLFM

**Comment by melaniefp** [comment]
Hello Kai,

The compilation message is correct. It is definitely an error of paths. Your Python is not finding the .so file. Could you verify the value of your python list of paths?

**Comment by xukai92** [comment]
### About path

I did have `sys.path.append('/Users/kai/projects/GLFM/src/GLFMpython')` before `import GLFM` - if I don't do so, I get a different error `ImportError: No module named GLFM` so I believe my Python know where GLFM is. 

### My guess of the cause of the error I meet

I guess this error is somehow explained by

```python
ImportError: dlopen(/Users/kai/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so, 2): Library not loaded: @rpath/libgsl.19.dylib
  Referenced from: /Users/kai/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so
  Reason: image not found
```

But I don't quite understand it, especially `Library not loaded: @rpath/libgsl.19.dylib`.

**Comment by melaniefp** [comment]
I see. Two paths should be visible in the python path: /GLFM/src/GLFMpython and GLFM/Ccode/wrapper_python.
The command that seems not to be working is:
sys.path.append('/Users/kai/projects/GLFM/Ccode/wrapper_python')

Do you get a different error when you comment this line?
Is this last path in your python PATH variable?

**Comment by xukai92** [comment]
I still get the same error when I tried to
  - comment out the path, or
  - change the path to `/Users/kai/projects/GLFM/src/Ccode/wrapper_python`

The last three entries of `sys.path` are

```python
 ['/Users/kai/projects/GLFM/src/GLFMpython',
 '/Users/kai/projects/GLFM/src/Ccode/wrapper_python',
 '/Users/kai/projects/GLFM/src/Ccode/wrapper_python/']
```

**Comment by melaniefp** [comment]
Hi Kai,

I think I know what is happening.
The GLFMlib.so object exists, but one required library (the GSL one) is missing or not found (see the Requirements list in the documentation). This prevents you to be able to import GLFM successfully.

Could you check whether the GSL library is properly installed for you?

(we plan to automatize these steps in the future, so your feedback is actually is very useful for us, thanks for that)

**Comment by xukai92** [comment]
I did followed the guide to install these 4 dependencies. As you asked, I checked the gsl one by calling the install command again, which gave below.

```bash
(glfm) ➜  GLFM (master) ✗ conda install -c pesoto cython_gsl=1.0.0
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/kai/miniconda2/envs/glfm:
#
cython_gsl                1.0.0                    py27_0    pesoto
(glfm) ➜  GLFM (master) ✗
```

**Comment by melaniefp** [comment]
The GLS library is installed, I see.

In that case, it seems to be a problem of the rpath (run-path dependent libraries) in OSX, i.e., the library is not properly linked. This is apparently a common problem in general:
[https://stackoverflow.com/questions/9263256/can-you-please-help-me-understand-how-mach-o-libraries-work-in-mac-os-x](url)
and
[https://github.com/conda/conda-build/issues/279](url)

I am not an expert on this, but I know this can be fixed somehow with the "otool" command, as explained in the first link.

I will need a bigger time window to come with a solution for this, I will let you know.
Meanwhile, let me know if you find a way around.

Thanks again!

**Comment by xukai92** [comment]
Hi, I somehow managed to get that linked by

```bash
install_name_tool -id @rpath/libgsl.19.dylib ~/miniconda2/envs/glfm/lib/libgsl.19.dylib
install_name_tool -add_rpath ~/miniconda2/envs/glfm/lib/ ~/projects/GLFM/src/Ccode/wrapper_python/GLFMlib.so
```

NOTE: I didn't understand that well but just gave some tries.

I don't have the error before but now I have a new one below:

```python
------------------------------------------------------------------
ImportError                      Traceback (most recent call last)
<ipython-input-3-7cfb7c4c83a0> in <module>()
      8 sys.path.append('/Users/kai/projects/GLFM/src/GLFMpython')
      9 # sys.path.append('/Users/kai/projects/GLFM/src/Ccode/wrapper_python')
---> 10 import GLFM
     11 
     12 import pdb

/Users/kai/projects/GLFM/src/GLFMpython/GLFM.py in <module>()
     11 sys.path.append(os.path.join(root, 'Ccode/wrapper_python/'))
     12 
---> 13 import GLFMlib # python wrapper library in order to run C++ inference routine
     14 import mapping_functions as mf
     15 

cymem.pxd in init GLFMlib (GLFM.cpp:6703)()

ImportError: No module named cymem.cymem
```

**Comment by melaniefp** [comment]
Great that you solved it!

About the new error, similar thing than previously it seems:
cymem is another library used by our package, and it seems that it was not correctly linked/located, etc...

I found a related trend about this:
[https://github.com/explosion/spaCy/issues/206](url)

I would suggest to remove the cymem library and install it again (newest version).

**Comment by melaniefp** [comment]
We will definitely work on making it easier to install all the needed dependencies/libraries in the future.

**Comment by xukai92** [comment]
I tried to reinstall cymen library but still have that problem.

Also FYI I also tried the whole procedure on my Linux machine (a clean installation of Ubuntu 17.04), which doesn't have the first linking problem but still says `ImportError: No module named cymem.cymem`. Any idea?

**Comment by melaniefp** [comment]
Hello Kai,

Apologies for the delay, I recently took quite long holidays and did not get any chance to answer you before that.

I am happy to announce you that we have automatized the installation process and verified all dependencies of the GLFM library. The procedure is much simpler now, that should solve the previous import errors you got. The documentation has been updated accordingly, here the summary:

Requirements: Anaconda + gcc compiler + qt functionality. The last two are basic packages that are generally already available, see documentation for install instructions in Ubuntu.

Installation: Simply git clone the newest repository, go to install folder, and execute installation script: bash install_for_python.sh

Please let me know if you encounter any other difficulty, will be more than happy to help.

**Comment by xukai92** [comment]
Hi,

Thanks for the update! No worries - I also had a long holiday and just returned to work :)

I will try that out later and let you know how it goes.

**Comment by melaniefp** [comment]
Great, thanks!

**Comment by 1065146** [comment]
@xukai92 Thanks for posting this. I encountered the exact same problems (dylib issue followed by cymem issue). I cloned the updated git but the issue does not seem to go away. Did you manage to fix it?

@melaniefp I found another relate link on the cymem issue https://github.com/explosion/spaCy/issues/502
It seems to occur when packaging apps. The link above did not get resolved though.

**Comment by xukai92** [comment]
@1065146 I just tried following the current install instructions and it went well (i.e. the test file `demo_GLFM_test.py` passes). 

FYI, my OS is Ubuntu 16.04.04, with fresh Anaconda Python 2.7 installation.

**Comment by melaniefp** [comment]
@1065146 Thank you for the info! It seems a little tricky to fix indeed. I tried to reproduce the error, but everything seems to work well for me, please let me know if you get that error still.
