### ISSUE TITLE
python installation

### ISSUE THREAD

**Issue by sandraleebatista** [ivaleraM/GLFM#5]
Hello, Hope you are doing well. I have been following the installation instructions for R and Python to no avail. For Python I have made the most progress. I had run the installation script with no errors. However, when I try to run the sample demo, I had many errors (mainly with using python3 that I could fix), but one I could not, the following:
 python demo_GLFM_test.py
Traceback (most recent call last):
  File "../GLFM/demos/python/demo_GLFM_test.py", line 8, in <module>
    import GLFM
  File "../GLFM/src/GLFMpython/GLFM.py", line 16, in <module>
    import GLFMlib # python wrapper library in order to run C++ inference routine
ImportError: libgsl.so.27: cannot open shared object file: No such file or directory

I am guessing it is with a GSL shared library but not sure. Do you have any suggestions?

Thank you, Sandra

**Comment by sandraleebatista** [comment]
Sorry just figured it out. Had to add path to GSL to my library path, but now there are more issues....

(i.e. LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to GSL lib>
export LD_LIBRARY_PATH)

**Comment by sandraleebatista** [comment]
Python 2.7 no longer supports numpy so trying to port to Python3. having a bit of difficulty. Here is most recent error:
GLFM.py", line 107, in infer
    GLFMlib.infer(Xin, tmp_data['C'], Zin, Fin, params['bias'], params['s2u'],\
  File "GLFM.pyx", line 126, in GLFMlib.infer
    print "In C++: transforming input data..."
TypeError: expected bytes, str found

**Comment by sandraleebatista** [comment]
Entering C++: Running Inference Routine...

N=3, D=5, K=2
Running inference algorithm (currently inside C++ routine...)
Before IT loop...
Nsim=1000
After IT loop...

Back to Python: OK

Kest=1, N=3

k=0, i=0
k=0, i=1
k=0, i=2
Z_out loaded
B_out[D,Kest,maxR] where D=5, Kest=1, maxR=3
gsl: submatrix_source.c:41: ERROR: second dimension overflows matrix
Default GSL error handler invoked.
Aborted (core dumped)

**Comment by melaniefp** [comment]
Hi Sandra. Thank you for reaching out. The error you are seeing  could be a version issue between GSL, and Cython. We are unfortunately not supporting this repo actively anymore. If you are still interested in using the repo, I can try to have a look in the next week or so, and let you know if I find any fix. If you figure out a way to fix it, we would really appreciate if you can continue keeping us posted and sharing your experience in this thread for future potentially interested users of the package, thanks.

**Comment by sandraleebatista** [comment]
Thank you, Melanie. If you are able to take a look, that would be appreciated. I will also see if I can get the R version working in the meantime.

**Comment by sandraleebatista** [comment]
Have R code running, but not Python. Have some errors with R code such as insisting on Z and params, but not sure what they should be set to...

**Comment by sandraleebatista** [comment]
R is working now and may not pursue Python more. I think it may be compatibility issues with Cython.
